#!/command/with-contenv /usr/local/bin/python3
import sys
from borgmatic.commands.borgmatic import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())