#!/bin/bash

ability () {
    host=$1
    shift 1
    connect_host="${HOST_OVERRIDE:-$host}"
    ssh borg@"$connect_host" \
        -i /run/secrets/borg_user_private_key \
        -o StrictHostKeyChecking=no \
        -qt ability "$@"
}

mount () {
    host=$1
    connect_host="${HOST_OVERRIDE:-$host}"

    if [ "$(ls -A "$PWD")" ]; then
        echo "Error: current directory is not empty"
        return 1
    fi

    sshfs \
        borg@"$connect_host":/ "$PWD" \
        -o IdentityFile=/run/secrets/borg_user_private_key \
        -o StrictHostKeyChecking=no \
        -o sftp_server="/usr/local/bin/ability mount-filesystem"
}

unmount () {
    umount -l "$PWD"
}

check-empty () {
    dir=$1
    if [ -n "$(ls -A "$dir" 2>/dev/null)" ]; then
        exit 75
    else
        exit 0
    fi
}

exclude-gitignore-files () {
    dir=$1
    out=$2
    find "$dir" -type f -name ".gitignore" | while read -r gitignore_file; do
        base_dir=$(dirname "$gitignore_file")
        grep -vE '^\s*#|^\s*$' "$gitignore_file" | while read -r line; do
            echo "$base_dir/$line" >> "$out"
        done
    done
}

"$1" "${@:2}"
