#!/bin/bash

# shellcheck source=../common
. "$(dirname "$0")"/../common

borg_umount_remote_filesystem jessie
borg_postgres_backup_clean jessie firefly-postgres
borg_postgres_backup_clean jessie immich-postgres
borg_postgres_backup_clean jessie nextcloud-postgres
borg_postgres_backup_clean jessie paperless-postgres
