#!/bin/sh

CONFIG_FILE="/config/rclone/rclone.conf"
MAX_ALLOWANCE_GB=15

if [ "$1" = "mount" ]; then
  UPSTREAMS=$(grep "upstreams = " "$CONFIG_FILE" | grep -o "google-drive-\d*: ")
  DRIVE_COUNT=$(echo "$UPSTREAMS" | wc -l)
  MAX_SIZE=$((DRIVE_COUNT * MAX_ALLOWANCE_GB))
  SIZE_ARG="--vfs-disk-space-total-size=${MAX_SIZE}G"
  exec rclone "$@" "$SIZE_ARG"
else
  exec rclone "$@"
fi
